name:                vanity-filter
version:             0.1.0.0
github:              "Shou/vanity-filter"
license:             BSD3
author:              "Benedict Aas"
maintainer:          "x@shou.io"
copyright:           "2018 Benedict Aas"

extra-source-files:
- README.md
- ChangeLog.md

# Metadata used when publishing your package
# synopsis:            Short description of your package
# category:            Web

# To avoid duplicated efforts in documentation and dealing with the
# complications of embedding Haddock markup inside cabal files, it is
# common to point users to the README.md file.
description:         Please see the README on Github at <https://github.com/githubuser/vanity-filter#readme>

dependencies:
- base >= 4.7 && < 5
- stm
- text
- process
- vector
- random
- bytestring
- bits
- hexstring
- cryptonite
- memory
- base32string
- lens
- containers

library:
  source-dirs: src

executables:
  nano-vanity-filter:
    main:                Main.hs
    source-dirs:         app
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - vanity-filter

tests:
  vanity-filter-test:
    main:                Spec.hs
    source-dirs:         test
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - vanity-filter
